title:              Clean Blog
email:              your-email@example.com
description:        Test
author:             Start Bootstrap
baseurl:            "/initiative-gegen-abfallsammelstelle.github.io"
url:                "https://initiative-gegen-abfallsammelstelle.github.io"

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
