title:              Initiative Gegen Abfallsammelstelle Mies/Eich
description:        Wir wehren uns gegen Lärm und Verkehrsüberlastung
email:              ulrich.schwesinger@gmail.com
formspree_id:       2596664108891765975
baseurl:            "/initiative-gegen-abfallsammelstelle.github.io"
url:                "https://initiative-gegen-abfallsammelstelle.github.io"

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
